version: "3.5"

services:
  ce0:
    build: src/
    image: alinmear/docker-conanexiles:latest
    restart: unless-stopped
    environment:
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=A Conan Exiles Server"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=verysecure123"
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=themostsecure1234"
      - "CONANEXILES_INSTANCENAME=exiles0"
      - "CONANEXILES_SERVER_TYPE=pve"
      - "UPDATE_MODS=+workshop_download_item 440900 1657730588"
      
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles/ConanSandbox/exiles0

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - redis:/data/

volumes:
    data:
    redis:
